---

name: AWS AMI using Packer

on:
  push:
    branches:
        - 'master'
env:
  PRODUCT_VERSION: "latest"
        

  # schedule:
  #   - cron:  '45 0 7 * *'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
          
      - name: Packer Init
        id: init
        run: "packer init ./aws-demo.pkr.hcl"

      - name: Packer Validate 
        id: validate
        run: "packer validate ./aws-demo.pkr.hcl"

      - name: Packer Build 
        id: build
        run: "packer build ./aws-demo.pkr.hcl"
